<a href="https://colab.research.google.com/github/arulbenjaminchandru/ai-architect-program/blob/main/models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 LLM Context Window & Pricing Comparison (2022–2026)

This notebook provides a consolidated dataset of:
- Model
- Company
- Release Year
- Context Window
- Token Pricing (Input & Output)

Useful for:
- RAG architecture decisions
- Cost optimization
- Model comparison

In [1]:
import pandas as pd

data = [
    # OpenAI
    ["GPT-3", "OpenAI", 2020, "2K–4K", 2.5, 3],
    ["GPT-3.5", "OpenAI", 2022, "4K–16K", 0.75, 1.5],
    ["GPT-4", "OpenAI", 2023, "8K–32K", 20, 45],
    ["GPT-4 Turbo", "OpenAI", 2023, "128K", 3, 10],
    ["GPT-4o", "OpenAI", 2024, "128K", 2.5, 10],
    ["GPT-4o Mini", "OpenAI", 2024, "128K", 0.15, 0.6],
    ["GPT-4.1", "OpenAI", 2025, "~1M", 3.5, 12],
    ["GPT-5.x", "OpenAI", "2025–26", "200K–400K", 10, 50],

    # Anthropic
    ["Claude 2", "Anthropic", 2023, "200K", 5, 15],
    ["Claude 3 Haiku", "Anthropic", 2024, "200K", 0.25, 1.25],
    ["Claude 3.5 Sonnet", "Anthropic", 2024, "200K", 3, 15],
    ["Claude Opus 4", "Anthropic", "2025–26", "~1M", 10, 50],

    # Google
    ["Gemini 1.0", "Google", 2023, "32K–128K", 1.5, 7],
    ["Gemini 1.5 Flash", "Google", 2024, "~1M", 1, 6],
    ["Gemini 1.5 Pro", "Google", 2024, "1M–2M", 2.5, 12],
    ["Gemini 2.x", "Google", "2025–26", "~1M+", 1, 8],

    # Meta
    ["LLaMA 1", "Meta", 2023, "2K–4K", 0, 0],
    ["LLaMA 2", "Meta", 2023, "4K–32K", 0.5, 1.5],
    ["LLaMA 3", "Meta", 2024, "8K–128K", 0.5, 1.5],
    ["LLaMA 4", "Meta", "2025–26", "1M–10M", 0.2, 0.5],

    # Others
    ["Mistral", "Mistral", 2023, "8K–32K", 0.2, 0.5],
    ["Mixtral", "Mistral", 2024, "32K–64K", 0.3, 0.8],
    ["DeepSeek V3", "DeepSeek", "2024–25", "128K", 0.14, 0.4],
    ["Grok", "xAI", "2025–26", "256K–2M", 0.2, 0.5],
    ["Qwen", "Alibaba", "2024–25", "32K–256K", 0.5, 2]
]

columns = [
    "Model",
    "Company",
    "Release Year",
    "Context Window",
    "Input Cost ($/1M tokens)",
    "Output Cost ($/1M tokens)"
]

df = pd.DataFrame(data, columns=columns)
df

,Model,Company,Release Year,Context Window,Input Cost ($/1M tokens),Output Cost ($/1M tokens)
0,GPT-3,OpenAI,2020,2K–4K,2.50,3.00
1,GPT-3.5,OpenAI,2022,4K–16K,0.75,1.50
2,GPT-4,OpenAI,2023,8K–32K,20.00,45.00
3,GPT-4 Turbo,OpenAI,2023,128K,3.00,10.00
4,GPT-4o,OpenAI,2024,128K,2.50,10.00
5,GPT-4o Mini,OpenAI,2024,128K,0.15,0.60
6,GPT-4.1,OpenAI,2025,~1M,3.50,12.00
7,GPT-5.x,OpenAI,2025–26,200K–400K,10.00,50.00
8,Claude 2,Anthropic,2023,200K,5.00,15.00
9,Claude 3 Haiku,Anthropic,2024,200K,0.25,1.25
10,Claude 3.5 Sonnet,Anthropic,2024,200K,3.00,15.00
11,Claude Opus 4,Anthropic,2025–26,~1M,10.00,50.00
12,Gemini 1.0,Google,2023,32K–128K,1.50,7.00
13,Gemini 1.5 Flash,Google,2024,~1M,1.00,6.00
14,Gemini 1.5 Pro,Google,2024,1M–2M,2.50,12.00
15,Gemini 2.x,Google,2025–26,~1M+,1.00,8.00
16,LLaMA 1,Meta,2023,2K–4K,0.00,0.00
17,LLaMA 2,Meta,2023,4K–32K,0.50,1.50
18,LLaMA 3,Meta,2024,8K–128K,0.50,1.50
19,LLaMA 4,Meta,2025–26,1M–10M,0.20,0.50
20,Mistral,Mistral,2023,8K–32K,0.20,0.50
21,Mixtral,Mistral,2024,32K–64K,0.30,0.80
22,DeepSeek V3,DeepSeek,2024–25,128K,0.14,0.40
23,Grok,xAI,2025–26,256K–2M,0.20,0.50
24,Qwen,Alibaba,2024–25,32K–256K,0.50,2.00

In [2]:
# Sort by cost efficiency (input cost)
df.sort_values(by="Input Cost ($/1M tokens)")

,Model,Company,Release Year,Context Window,Input Cost ($/1M tokens),Output Cost ($/1M tokens)
16,LLaMA 1,Meta,2023,2K–4K,0.00,0.00
22,DeepSeek V3,DeepSeek,2024–25,128K,0.14,0.40
5,GPT-4o Mini,OpenAI,2024,128K,0.15,0.60
20,Mistral,Mistral,2023,8K–32K,0.20,0.50
19,LLaMA 4,Meta,2025–26,1M–10M,0.20,0.50
23,Grok,xAI,2025–26,256K–2M,0.20,0.50
9,Claude 3 Haiku,Anthropic,2024,200K,0.25,1.25
21,Mixtral,Mistral,2024,32K–64K,0.30,0.80
17,LLaMA 2,Meta,2023,4K–32K,0.50,1.50
18,LLaMA 3,Meta,2024,8K–128K,0.50,1.50
24,Qwen,Alibaba,2024–25,32K–256K,0.50,2.00
1,GPT-3.5,OpenAI,2022,4K–16K,0.75,1.50
15,Gemini 2.x,Google,2025–26,~1M+,1.00,8.00
13,Gemini 1.5 Flash,Google,2024,~1M,1.00,6.00
12,Gemini 1.0,Google,2023,32K–128K,1.50,7.00
4,GPT-4o,OpenAI,2024,128K,2.50,10.00
0,GPT-3,OpenAI,2020,2K–4K,2.50,3.00
14,Gemini 1.5 Pro,Google,2024,1M–2M,2.50,12.00
10,Claude 3.5 Sonnet,Anthropic,2024,200K,3.00,15.00
3,GPT-4 Turbo,OpenAI,2023,128K,3.00,10.00
6,GPT-4.1,OpenAI,2025,~1M,3.50,12.00
8,Claude 2,Anthropic,2023,200K,5.00,15.00
7,GPT-5.x,OpenAI,2025–26,200K–400K,10.00,50.00
11,Claude Opus 4,Anthropic,2025–26,~1M,10.00,50.00
2,GPT-4,OpenAI,2023,8K–32K,20.00,45.00

In [3]:
# Filter: Long context models (>100K)
df[df["Context Window"].str.contains("K|M")]

,Model,Company,Release Year,Context Window,Input Cost ($/1M tokens),Output Cost ($/1M tokens)
0,GPT-3,OpenAI,2020,2K–4K,2.50,3.00
1,GPT-3.5,OpenAI,2022,4K–16K,0.75,1.50
2,GPT-4,OpenAI,2023,8K–32K,20.00,45.00
3,GPT-4 Turbo,OpenAI,2023,128K,3.00,10.00
4,GPT-4o,OpenAI,2024,128K,2.50,10.00
5,GPT-4o Mini,OpenAI,2024,128K,0.15,0.60
6,GPT-4.1,OpenAI,2025,~1M,3.50,12.00
7,GPT-5.x,OpenAI,2025–26,200K–400K,10.00,50.00
8,Claude 2,Anthropic,2023,200K,5.00,15.00
9,Claude 3 Haiku,Anthropic,2024,200K,0.25,1.25
10,Claude 3.5 Sonnet,Anthropic,2024,200K,3.00,15.00
11,Claude Opus 4,Anthropic,2025–26,~1M,10.00,50.00
12,Gemini 1.0,Google,2023,32K–128K,1.50,7.00
13,Gemini 1.5 Flash,Google,2024,~1M,1.00,6.00
14,Gemini 1.5 Pro,Google,2024,1M–2M,2.50,12.00
15,Gemini 2.x,Google,2025–26,~1M+,1.00,8.00
16,LLaMA 1,Meta,2023,2K–4K,0.00,0.00
17,LLaMA 2,Meta,2023,4K–32K,0.50,1.50
18,LLaMA 3,Meta,2024,8K–128K,0.50,1.50
19,LLaMA 4,Meta,2025–26,1M–10M,0.20,0.50
20,Mistral,Mistral,2023,8K–32K,0.20,0.50
21,Mixtral,Mistral,2024,32K–64K,0.30,0.80
22,DeepSeek V3,DeepSeek,2024–25,128K,0.14,0.40
23,Grok,xAI,2025–26,256K–2M,0.20,0.50
24,Qwen,Alibaba,2024–25,32K–256K,0.50,2.00

## 📌 Insights

- Cheapest models: DeepSeek, Grok, Mistral
- Best long-context: Gemini 1.5 Pro, Claude Opus, GPT-4.1
- Best balance: GPT-4o, Claude Sonnet
- Output tokens cost significantly more than input tokens

👉 Use routing strategies to optimize cost (cheap model + premium fallback)